datasets=[
    dict(abbr='openai_humaneval',
        eval_cfg=dict(
            evaluator=dict(
                type='opencompass.datasets.HumanEvalEvaluator'),
            k=[
                1,
                10,
                100,
                ],
            pred_postprocessor=dict(
                type='opencompass.datasets.humaneval_postprocess_v2'),
            pred_role='BOT'),
        infer_cfg=dict(
            inferencer=dict(
                max_out_len=512,
                type='opencompass.openicl.icl_inferencer.GenInferencer'),
            prompt_template=dict(
                template=dict(
                    round=[
                        dict(prompt='Complete the following python code:\n{prompt}',
                            role='HUMAN'),
                        ]),
                type='opencompass.openicl.icl_prompt_template.PromptTemplate'),
            retriever=dict(
                type='opencompass.openicl.icl_retriever.ZeroRetriever')),
        path='opencompass/humaneval',
        reader_cfg=dict(
            input_columns=[
                'prompt',
                ],
            output_column='task_id',
            train_split='test'),
        type='opencompass.datasets.HumanevalDataset'),
    ]
eval_cfg=dict(
    batch_size=1,
    batch_size_=1,
    diff_confidence_eos_eot_inf=True,
    diff_logits_eos_inf=False,
    gen_blocksize=16,
    gen_length=512,
    gen_steps=512)
humaneval_datasets=[
    dict(abbr='openai_humaneval',
        eval_cfg=dict(
            evaluator=dict(
                type='opencompass.datasets.HumanEvalEvaluator'),
            k=[
                1,
                10,
                100,
                ],
            pred_postprocessor=dict(
                type='opencompass.datasets.humaneval_postprocess_v2'),
            pred_role='BOT'),
        infer_cfg=dict(
            inferencer=dict(
                max_out_len=512,
                type='opencompass.openicl.icl_inferencer.GenInferencer'),
            prompt_template=dict(
                template=dict(
                    round=[
                        dict(prompt='Complete the following python code:\n{prompt}',
                            role='HUMAN'),
                        ]),
                type='opencompass.openicl.icl_prompt_template.PromptTemplate'),
            retriever=dict(
                type='opencompass.openicl.icl_retriever.ZeroRetriever')),
        path='opencompass/humaneval',
        reader_cfg=dict(
            input_columns=[
                'prompt',
                ],
            output_column='task_id',
            train_split='test'),
        type='opencompass.datasets.HumanevalDataset'),
    ]
infer=dict(
    partitioner=dict(
        min_task_size=16,
        num_split=None,
        num_worker=8,
        type='opencompass.partitioners.NumWorkerPartitioner'),
    runner=dict(
        max_num_workers=64,
        retry=5,
        task=dict(
            type='opencompass.tasks.OpenICLInferTask'),
        type='opencompass.runners.LocalRunner'))
llada_instruct_8b_models=[
    dict(abbr='llada-1.5-8b-instruct',
        batch_size=1,
        batch_size_=1,
        diff_confidence_eos_eot_inf=True,
        diff_logits_eos_inf=False,
        gen_blocksize=16,
        gen_length=512,
        gen_steps=512,
        max_out_len=1024,
        path='GSAI-ML/LLaDA-1.5',
        run_cfg=dict(
            num_gpus=1),
        type='opencompass.models.LLaDAModel'),
    ]
model=dict(
    abbr='llada-1.5-8b-instruct',
    batch_size=1,
    batch_size_=1,
    diff_confidence_eos_eot_inf=True,
    diff_logits_eos_inf=False,
    gen_blocksize=16,
    gen_length=512,
    gen_steps=512,
    max_out_len=1024,
    path='GSAI-ML/LLaDA-1.5',
    run_cfg=dict(
        num_gpus=1),
    type='opencompass.models.LLaDAModel')
models=[
    dict(abbr='llada-1.5-8b-instruct',
        batch_size=1,
        batch_size_=1,
        diff_confidence_eos_eot_inf=True,
        diff_logits_eos_inf=False,
        gen_blocksize=16,
        gen_length=512,
        gen_steps=512,
        max_out_len=1024,
        path='GSAI-ML/LLaDA-1.5',
        run_cfg=dict(
            num_gpus=1),
        type='opencompass.models.LLaDAModel'),
    ]
